# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: d2s9rgkrqa51hl
  pool: 5
  user: knuolizyappclc
  password: bsIeo6e1nnowQDPSI4RVw9XLef
  host: ec2-107-20-153-141.compute-1.amazonaws.com
  port: 5432